In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Define an example input tensor of size 5x5 and a custom kernel as PyTorch tensors
input_image = torch.tensor([[0.1, 0.2, 0.3, 0.4, 0.5],
                            [0.2, 0.3, 0.4, 0.5, 0.6],
                            [0.3, 0.4, 0.5, 0.6, 0.7],
                            [0.4, 0.5, 0.6, 0.7, 0.8],
                            [0.5, 0.6, 0.7, 0.8, 0.9]], dtype=torch.float32)

# Convert the input image to a 4D tensor (batch size of 1, number of channels, height, width)
input_image = input_image.unsqueeze(0).unsqueeze(0)

kernel = torch.tensor([[0, -1, 0],
                       [-1, 6, -1],
                       [0, -1, 0]], dtype=torch.float32)

# Convert the kernel to a 4D tensor (number of output channels, number of input channels, kernel height, kernel width)
kernel = kernel.unsqueeze(0).unsqueeze(0)

# Create a convolutional layer with the custom kernel
conv_layer = nn.Conv2d(1, 1, kernel_size=3, padding=0, bias=False)

relu_layer = nn.ReLU()

pad_layer = nn.MaxPool2d(2, stride=1)

# Set the weight of the convolutional layer to the custom kernel
conv_layer.weight.data = kernel

# Perform convolution
output = conv_layer(input_image)
relu_output = relu_layer(output)
pool_output = pad_layer(relu_output)

# Print the result
print(relu_output)
print(pool_output)


tensor([[[[0.6000, 0.8000, 1.0000],
          [0.8000, 1.0000, 1.2000],
          [1.0000, 1.2000, 1.4000]]]], grad_fn=<ReluBackward0>)
tensor([[[[1.0000, 1.2000],
          [1.2000, 1.4000]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)


In [8]:
import torch
import torch.nn as nn
from torchinfo import summary

class SimpleNeuralNetwork(nn.Module):
    def __init__(self):
        super(SimpleNeuralNetwork, self).__init__()
        # Define the layers of the neural network
        self.conv1 = nn.Conv2d(3, 150, 11)
        self.conv2 = nn.Conv2d(150, 75, 8, stride=2, padding=1)
        self.pool1 = nn.MaxPool2d(2, stride=2)

        self.flatten = nn.Flatten(start_dim=0)

        self.fc1 = nn.Linear(63075, 300)
        self.fc2 = nn.Linear(300, 20)

    def forward(self, x):
        # Define the forward pass of the neural network
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.pool1(x)
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.fc2(x)
        return x

model = SimpleNeuralNetwork()

print(summary(model, input_size=(3, 130, 130)))


Layer (type:depth-idx)                   Output Shape              Param #
SimpleNeuralNetwork                      [20]                      --
├─Conv2d: 1-1                            [150, 120, 120]           54,600
├─Conv2d: 1-2                            [75, 58, 58]              720,075
├─MaxPool2d: 1-3                         [75, 29, 29]              --
├─Flatten: 1-4                           [63075]                   --
├─Linear: 1-5                            [300]                     18,922,800
├─Linear: 1-6                            [20]                      6,020
Total params: 19,703,495
Trainable params: 19,703,495
Non-trainable params: 0
Total mult-adds (G): 9.79
Input size (MB): 0.20
Forward/backward pass size (MB): 19.30
Params size (MB): 78.81
Estimated Total Size (MB): 98.32


In [9]:
import torch
import torch.nn.functional as F

# Input tensor
input_tensor = torch.tensor([3.0, 2.0, 3.0])

# Apply softmax activation
output_tensor = F.softmax(input_tensor, dim=0)

# Print the output tensor
print(output_tensor)


tensor([0.4223, 0.1554, 0.4223])


In [13]:
crossEN = nn.CrossEntropyLoss()

input_tensor = torch.tensor([3.0, 2.0, 3.0])
target_tensor = torch.tensor([0.0, 1.0, 0.0])

output = crossEN(input_tensor, target_tensor)
print(output)

tensor(1.8620)
